### ISSUE TITLE
Admin Auth System

### ISSUE THREAD

**Issue by KaviiSuri** [scortier/NITS-Result-Portal#9]
# TODO
- [x] Admin Model Setup with roles (moderator, viewer) @debojyoti1915001
- [x] Admin Auth Middlewares with role-based authentication @KaviiSuri 
- [x] Signup route for owner @reeyah
- [x] Signup and Create routes for moderators and viewers @Jitulteron7 
- [x]  Signout Route @aditya2712

### Ideas
- we can have a separate cookie and  a different expiry time for admins
- we can have a function that takes in a role and returns a middleware function to verify that role to reduce code duplication for each role
- should we have an "upgrade" route to change the admin roles of an existing admin?

**Comment by KaviiSuri** [comment]
**Review Request**
@knight-18

**Comment by knight-18** [comment]
We'll think about upgrading the role later if needed. Not needed iright now.
Provide a description of the second point @KaviiSuri .

**Comment by KaviiSuri** [comment]
> We'll think about upgrading the role later if needed. Not needed iright now.
> Provide a description of the second point @KaviiSuri .
@knight-18 

Basically, instead having functions like 
AuthMod
AuthViewer

We can have a function or class that takes in "viewer" or "mod" and output a function that verifies the specified role
Maybe like instead of authMod we use auth('mod') or Auth("mod").verify {which is a function} this way, the code is dry and a plus point is that if we ever need to rename or change or add a new role, we don't need to reimplement

**Comment by knight-18** [comment]
The point is for any role we are using the same schema `admin`. So even after auth we just need to know the role of the user. A common middleware will do.

**Comment by KaviiSuri** [comment]
> The point is for any role we are using the same schema `admin`. So even after auth we just need to know the role of the user. A common middleware will do.

Yeah, we are using the same schema, that was the point, why do we need to write 2 functions which are exactly the same except the line

`admin.role === 'mod' `
 To manage permissions

**Comment by knight-18** [comment]
Yes, Use only one middleware. No need for separate middlewares.
